[Appearance]
color_scheme_path=/home/uryu/.config/qt5ct/colors/Kripton.conf
custom_palette=true
icon_theme=cyberpunk-technotronic
standard_dialogs=default
style=Fusion

[Fonts]
fixed="Maple Mono NF,11,-1,5,50,0,0,0,0,0"
general="Maple Mono NF,11,-1,5,50,0,0,0,0,0"

[Interface]
cursor_flash_time=1000
menus_have_icons=true
show_shortcuts_in_context_menus=true
toolbutton_style=4
