set $laptop eDP-1
default_border pixel 2
gaps inner 5
gaps outer 5
smart_gaps on
output HDMI-A-1 mode 1920x1080@74.973Hz

#                       <border>    <background> <text>      <indicator> <child_border>
client.focused          #9bbfbf     #131519      #E0E0E0     #9bbfbf     #9bbfbf
client.unfocused        #9bbfbf     #131519      #7c7d80     #9bbfbf     #9bbfbf
client.focused_inactive #9bbfbf     #131519      #7c7d80     #9bbfbf     #9bbfbf
client.urgent           #cd3520     #cd3520      #E0E0E0     #cd3520     #cd3520

# Exousia theme RPMs: Bibata cursor + Maple Mono NF title/bar font
seat seat0 xcursor_theme Bibata-Modern-Classic 24
font pango:Maple Mono NF 11

set $wob wob

exec_always {
systemctl --user import-environment
gsettings set org.gnome.desktop.interface gtk-theme 'Kripton'
gsettings set org.gnome.desktop.interface icon-theme 'cyberpunk-technotronic'
gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
gsettings set org.gnome.desktop.interface cursor-size 24
gsettings set org.gnome.desktop.interface font-name 'Maple Mono NF 11'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
autotiling-rs
/usr/libexec/lxqt-policykit-agent
lid
test -e $SWAYSOCK.wob || mkfifo $SWAYSOCK.wob
tail -f $SWAYSOCK.wob | $wob
swaync
}
